<?php

declare(strict_types=1);

namespace App\Data;

use App\Models\Account;
use Spatie\LaravelData\Data;
use Spatie\TypeScriptTransformer\Attributes\TypeScript;

#[TypeScript('Account')]
class AccountData extends Data
{
    public function __construct(
        public string $ulid,
        public string $name,
        public ?string $color,
        public bool $autoGenerated,
        public ?string $accountNumber,
        public float $balance,
        public ?string $lastActivity,
        public ?float $interestRate,
        public ?string $description,
        public ?AccountCategoryData $category,
    ) {}

    public static function fromModel(Account $account): self
    {
        return new self(
            ulid: $account->ulid,
            name: $account->name,
            color: $account->color,
            autoGenerated: $account->auto_generated,
            accountNumber: $account->account_number,
            balance: $account->balance,
            lastActivity: null,
            interestRate: $account->interest_rate,
            description: $account->description,
            category: $account->relationLoaded('category')
                ? new AccountCategoryData(
                    ulid: $account->category->ulid,
                    name: $account->category->name,
                    type: $account->category->type,
                    color: $account->category->color
                )
                : null
        );
    }
}
