declare namespace App.Data {
export type AccountCategory = {
ulid: string;
name: string;
type: App.Enums.AccountType;
color: string;
accounts: Account[];
};
export type Account = {
ulid: string;
name: string;
color: string | null;
autoGenerated: boolean;
accountNumber: string | null;
balance: string;
lastActivity: string | null;
interestRate: number | null;
description: string | null;
category: App.Data.AccountCategory | null;
};
}
declare namespace App.Enums {
export enum AccountType { ASSET = 'Asset account', BENEFICIARY = 'Beneficiary account', CASH = 'Cash account', CREDIT_CARD = 'Credit card', DEBT = 'Debt', DEFAULT = 'Default account', EXPENSE = 'Expense account', IMPORT = 'Import account', INITIAL_BALANCE = 'Initial balance account', LIABILITY = 'Liability account', LOAN = 'Loan', MORTGAGE = 'Mortgage', RECONCILIATION = 'Reconciliation account', REVENUE = 'Revenue account' };
export enum AutoBudgetType { NONE = 0, RESETS_PERIODICALLY = 1, GROWS_PERIODICALLY = 2, ADJUSTS_FOR_EXPENSES_PERIODICALLY = 3 };
export enum Period { DAILY = 'Daily', WEEKLY = 'Weekly', MONTHLY = 'Monthly', SEMI_ANNUALLY = 'Every half a year', ANNUALLY = 'Annually' };
export enum TransactionType { DEPOSIT = 'Deposit', INVALID = 'Invalid', LIABILITY_CREDIT = 'Liability credit', OPENING_BALANCE = 'Opening balance', RECONCILIATION = 'Reconciliation', TRANSFER = 'Transfer', WITHDRAWAL = 'Withdrawal' };
}
